#! /bin/bash
NOMBRE_ZIP="tp0.zip"
NOMBRE_LATEX="informetp0"
ARCHIVOS_CODIGO=$(echo "arg_parse.s main.s src/Makefile " src/*.{c,h})
ENUNCIADO="6620-2c2013-tp0.pdf"

rm -rf entrega
mkdir entrega

echo "Compilando latex"
if  which rubber &> /dev/null ; then
	rubber --inplace --pdf informe/$NOMBRE_LATEX.tex &> /dev/null
else
	if which pdflatex &> /dev/null ; then
		cd informe
		pdflatex $NOMBRE_LATEX.tex &> /dev/null
		cd ../
	else
		echo "No hay compilador de latex"
		exit 1
	fi
fi

rm -f informe/$NOMBRE_LATEX.log informe/$NOMBRE_LATEX.aux

if ! mv informe/$NOMBRE_LATEX.pdf entrega/informe.pdf ; then
	echo "[ERROR]"
	exit 1
fi

echo "[Ok]"

echo "Copiando codigo fuente"
mkdir entrega/src
cp src/*.{h,c} entrega/src/
cp src/Makefile entrega/src/

echo "[Ok]"

if which a2ps &> /dev/null ; then
	if ! which ps2pdf &> /dev/null; then
		echo "[ERROR] No se tiene el programa ps2pdf"
		exit 1
	fi

	a2ps -A fill --toc $ARCHIVOS_CODIGO -o entrega/codigo.ps &> /dev/null
	ps2pdf entrega/codigo.ps entrega/codigo.pdf
	rm entrega/codigo.ps

else
	echo "[ERROR] No se puede generar pdf con codigo"
	exit 1
fi

echo "Agregando enunciado"
if ! cp $ENUNCIADO entrega ; then
	echo "[ERROR]"
	exit 1
fi

echo "Creando zip $NOMBRE_ZIP"

rm $NOMBRE_ZIP -f
cd entrega
zip ../$NOMBRE_ZIP -r ./* &> /dev/null
if [ $? -ne 0 ] ; then
	echo "[ERROR] Creando zip"
	exit 1
fi

cd ../

rm -rf entrega

exit 0
